name: tube-digest
services:
  tubedigest-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tubedigest-web
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - ../.env
    environment:
      - BACKEND_BASE_URL=${VITE_BACKEND_URL}
      - APP_ENV=production
